# This workflow will check style using Ruff.

name: Ruff Style Check

on:
  push:
    branches: [main,dev]
  pull_request:
    branches: [main,dev]

permissions:
  contents: write

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run ruff
        run: |
          ruff check --fix .
      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet || echo "CHANGES_DETECTED=true" >> $GITHUB_ENV

      - name: Commit changes
        if: env.CHANGES_DETECTED == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Apply ruff fixes"
          branch: ${{ github.head_ref }}
          commit_options: '--no-verify --signoff'
          file_pattern: '*.py'